#!/usr/bin/env python3
"""Generate C marshalling code from a protocol XML file.

  wscan.py <protocol.xml> <out dir>

Writes <name>-client.h, <name>-client.c, <name>-server.h and
<name>-server.c. Client side: one function per request (marshal), one
listener structure per interface with a callback per event. Server
side: one function per event (marshal), one listener structure per
interface with a callback per request. Both sides share interface
descriptors (name, version, message signatures) used by libwire.
"""
import sys
import xml.etree.ElementTree as ET

TYPE_CH = {"int": "i", "uint": "u", "fixed": "f", "string": "s", "array": "a", "object": "o", "new_id": "n", "fd": "h"}
CTYPE = {"int": "int32_t", "uint": "uint32_t", "fixed": "int32_t", "string": "const char *",
         "array": "const struct wire_array *", "object": "struct wire_object *", "new_id": "uint32_t", "fd": "int"}


def load(path):
    root = ET.parse(path).getroot()
    proto = {"name": root.get("name"), "interfaces": []}
    for iface in root.findall("interface"):
        msgs = {"request": [], "event": []}
        for kind in ("request", "event"):
            for m in iface.findall(kind):
                args = [{"name": a.get("name"), "type": a.get("type"), "interface": a.get("interface"),
                         "nullable": a.get("allow-null") == "true"} for a in m.findall("arg")]
                msgs[kind].append({"name": m.get("name"), "args": args, "destructor": m.get("type") == "destructor"})
        proto["interfaces"].append({"name": iface.get("name"), "version": int(iface.get("version")), **msgs})
    return proto


def signature(msg):
    s = ""
    for a in msg["args"]:
        s += ("?" if a["nullable"] else "") + TYPE_CH[a["type"]]
    return s


def descriptors(proto, out):
    """Interface descriptors shared by both sides, emitted once per file."""
    for iface in proto["interfaces"]:
        for kind in ("request", "event"):
            out.append("static const struct wire_message %s_%ss[] = {" % (iface["name"], kind))
            for m in iface[kind]:
                types = ", ".join(('"%s"' % a["interface"]) if a["interface"] else "NULL" for a in m["args"]) or "NULL"
                out.append('    { "%s", "%s", %d, (const char *const[]){ %s }, %d },' % (m["name"], signature(m), len(m["args"]), types, 1 if m["destructor"] else 0))
            if not iface[kind]:
                out.append("    { NULL, \"\", 0, NULL, 0 },")
            out.append("};")
    for iface in proto["interfaces"]:
        out.append('const struct wire_interface %s_interface = { "%s", %d, %d, %s_requests, %d, %s_events };' % (
            iface["name"], iface["name"], iface["version"], len(iface["request"]), iface["name"], len(iface["event"]), iface["name"]))


def args_decl(msg, side_object):
    parts = [side_object]
    for a in msg["args"]:
        if a["type"] == "new_id" and side_object.startswith("struct wire_proxy"):
            continue                      # the client allocates the id
        parts.append("%s %s" % (CTYPE[a["type"]], a["name"]))
    return ", ".join(parts)


def gen_client(proto, outdir):
    n = proto["name"]
    h = ["/* Generated by tools/wscan/wscan.py from protocol/%s.xml. Do not edit. */" % n,
         "#pragma once", "#include <wire/client.h>"] + (['#include "core-client.h"'] if n != "core" else []) + [""]
    c = ["/* Generated by tools/wscan/wscan.py from protocol/%s.xml. Do not edit. */" % n,
         '#include "%s-client.h"' % n, "#include <stddef.h>", ""]
    for iface in proto["interfaces"]:
        h.append("extern const struct wire_interface %s_interface;" % iface["name"])
    h.append("")
    for iface in proto["interfaces"]:
        name = iface["name"]
        # Event listener.
        h.append("struct %s_listener {" % name)
        for m in iface["event"]:
            params = ["void *user", "struct wire_proxy *self"]
            for a in m["args"]:
                params.append("%s %s" % ("struct wire_proxy *" if a["type"] in ("object", "new_id") else CTYPE[a["type"]], a["name"]))
            h.append("    void (*%s)(%s);" % (m["name"], ", ".join(params)))
        if not iface["event"]:
            h.append("    int unused;")
        h.append("};")
        h.append("static inline int %s_add_listener(struct wire_proxy *p, const struct %s_listener *l, void *user)" % (name, name))
        h.append("{ return wire_proxy_add_listener(p, (const void *)l, user); }")
        # Requests.
        for op, m in enumerate(iface["request"]):
            new_ids = [a for a in m["args"] if a["type"] == "new_id"]
            ret = "struct wire_proxy *" if new_ids else "void"
            params = ["struct wire_proxy *%s" % name]
            for a in m["args"]:
                if a["type"] == "new_id":
                    if not a["interface"]:
                        params.append("const struct wire_interface *new_interface")
                        params.append("int new_version")
                    continue
                params.append("%s %s" % ("struct wire_proxy *" if a["type"] == "object" else CTYPE[a["type"]], a["name"]))
            proto_line = "%s %s_%s(%s)" % (ret, name, m["name"], ", ".join(params))
            h.append(proto_line + ";")
            c.append(proto_line)
            c.append("{")
            c.append("    union wire_arg args[%d] = { { 0 } };" % max(1, len(m["args"])))
            if new_ids:
                c.append("    struct wire_proxy *created = NULL;")
            for i, a in enumerate(m["args"]):
                t = a["type"]
                if t in ("int", "fixed"):
                    c.append("    args[%d].i = %s;" % (i, a["name"]))
                elif t == "uint":
                    c.append("    args[%d].u = %s;" % (i, a["name"]))
                elif t == "string":
                    c.append("    args[%d].s = %s;" % (i, a["name"]))
                elif t == "array":
                    c.append("    args[%d].a = %s;" % (i, a["name"]))
                elif t == "object":
                    c.append("    args[%d].o = %s ? %s->obj.id : 0;" % (i, a["name"], a["name"]))
                elif t == "fd":
                    c.append("    args[%d].h = %s;" % (i, a["name"]))
                elif t == "new_id":
                    if a["interface"]:
                        c.append("    created = wire_proxy_create(%s, &%s_interface, %s_interface.version);" % (name, a["interface"], a["interface"]))
                    else:
                        c.append("    created = wire_proxy_create(%s, new_interface, new_version);" % name)
                    c.append("    if (!created)")
                    c.append("        return NULL;")
                    c.append("    args[%d].n = created->obj.id;" % i)
            c.append("    wire_proxy_marshal(%s, %d, args%s);" % (name, op, ", created" if new_ids else ", NULL"))
            if m["destructor"]:
                c.append("    wire_proxy_destroy(%s);" % name)
            if new_ids:
                c.append("    return created;")
            c.append("}")
            c.append("")
        h.append("")
    open("%s/%s-client.h" % (outdir, n), "w").write("\n".join(h) + "\n")
    open("%s/%s-client.c" % (outdir, n), "w").write("\n".join(c) + "\n")


def gen_server(proto, outdir):
    n = proto["name"]
    h = ["/* Generated by tools/wscan/wscan.py from protocol/%s.xml. Do not edit. */" % n,
         "#pragma once", "#include <wire/server.h>"] + (['#include "core-server.h"'] if n != "core" else []) + [""]
    c = ["/* Generated by tools/wscan/wscan.py from protocol/%s.xml. Do not edit. */" % n,
         '#include "%s-server.h"' % n, "#include <stddef.h>", ""]
    for iface in proto["interfaces"]:
        h.append("extern const struct wire_interface %s_interface;" % iface["name"])
    h.append("")
    for iface in proto["interfaces"]:
        name = iface["name"]
        # Request handlers (the implementation).
        h.append("struct %s_impl {" % name)
        for m in iface["request"]:
            params = ["struct wire_client *client", "struct wire_resource *self"]
            for a in m["args"]:
                params.append("%s %s" % ("struct wire_resource *" if a["type"] == "object" else CTYPE[a["type"]], a["name"]))
            h.append("    void (*%s)(%s);" % (m["name"], ", ".join(params)))
        if not iface["request"]:
            h.append("    int unused;")
        h.append("};")
        # Events.
        for op, m in enumerate(iface["event"]):
            params = ["struct wire_resource *%s" % name]
            for a in m["args"]:
                params.append("%s %s" % ("struct wire_resource *" if a["type"] in ("object", "new_id") else CTYPE[a["type"]], a["name"]))
            proto_line = "void %s_send_%s(%s)" % (name, m["name"], ", ".join(params))
            h.append(proto_line + ";")
            c.append(proto_line)
            c.append("{")
            c.append("    union wire_arg args[%d] = { { 0 } };" % max(1, len(m["args"])))
            for i, a in enumerate(m["args"]):
                t = a["type"]
                if t in ("int", "fixed"):
                    c.append("    args[%d].i = %s;" % (i, a["name"]))
                elif t == "uint":
                    c.append("    args[%d].u = %s;" % (i, a["name"]))
                elif t == "string":
                    c.append("    args[%d].s = %s;" % (i, a["name"]))
                elif t == "array":
                    c.append("    args[%d].a = %s;" % (i, a["name"]))
                elif t in ("object", "new_id"):
                    c.append("    args[%d].o = %s ? %s->obj.id : 0;" % (i, a["name"], a["name"]))
                elif t == "fd":
                    c.append("    args[%d].h = %s;" % (i, a["name"]))
            c.append("    wire_resource_post(%s, %d, args);" % (name, op))
            c.append("}")
            c.append("")
        h.append("")
    open("%s/%s-server.h" % (outdir, n), "w").write("\n".join(h) + "\n")
    open("%s/%s-server.c" % (outdir, n), "w").write("\n".join(c) + "\n")


def gen_interfaces(proto, outdir):
    n = proto["name"]
    c = ["/* Generated by tools/wscan/wscan.py from protocol/%s.xml. Do not edit. */" % n,
         "#include <wire/common.h>", "#include <stddef.h>", ""]
    for iface in proto["interfaces"]:
        c.append("extern const struct wire_interface %s_interface;" % iface["name"])
    c.append("")
    descriptors(proto, c)
    open("%s/%s-interfaces.c" % (outdir, n), "w").write("\n".join(c) + "\n")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    proto = load(sys.argv[1])
    gen_client(proto, sys.argv[2])
    gen_server(proto, sys.argv[2])
    gen_interfaces(proto, sys.argv[2])
