#!/usr/bin/env python3
"""Generate kernel/drivers/font.c, an 8x16 bitmap font for ISO 8859-1.

The glyphs come from the X11 "misc-fixed" 7x14 font (public domain), stored
next to this script as 7x14.pcf.gz. Each 7x14 glyph is placed in an 8x16 cell
with one blank row above and below and one blank column on the right.

Usage: genfont.py > kernel/drivers/font.c   (requires Pillow)
       genfont.py mfnt <font.ttf> <pixel size> <out.mfnt>

The second form writes a variable width 1 bit font for libgui (see
libgui/include/gui/gfx.h for the layout): a 16 byte header, 256 advances,
256 widths, then 256 glyph bitmaps of height rows of 32 bits, bit 31
leftmost. Glyphs wider than 32 pixels are clipped.
"""
import struct
import gzip
import io
import os
import sys
import tempfile

from PIL import Image, ImageDraw, ImageFont
from PIL.PcfFontFile import PcfFontFile

HERE = os.path.dirname(os.path.abspath(__file__))
PCF = os.path.join(HERE, "7x14.pcf.gz")
CELL_W, CELL_H = 8, 16
GLYPH_W, GLYPH_H = 7, 14

def load_font():
    data = gzip.open(PCF).read()
    with tempfile.TemporaryDirectory() as tmp:
        base = os.path.join(tmp, "font")
        PcfFontFile(io.BytesIO(data)).save(base)
        return ImageFont.load(base + ".pil")

def render(font, code):
    im = Image.new("1", (CELL_W, CELL_H), 0)
    ImageDraw.Draw(im).text((0, (CELL_H - GLYPH_H) // 2), chr(code), font=font, fill=1)
    rows = []
    for y in range(CELL_H):
        byte = 0
        for x in range(CELL_W):
            if im.getpixel((x, y)):
                byte |= 0x80 >> x
        rows.append(byte)
    return rows

def gen_mfnt(ttf, px, out):
    font = ImageFont.truetype(ttf, px)
    ascent, descent = font.getmetrics()
    height = ascent + descent
    advances, widths, bitmaps = [], [], []
    for code in range(256):
        if code < 32 or code == 127 or (128 <= code < 160):
            advances.append(0)
            widths.append(0)
            bitmaps.append([0] * height)
            continue
        ch = chr(code)
        adv = int(round(font.getlength(ch)))
        # Render on a wide canvas; the glyph may start left of x = 0.
        pad = 4
        im = Image.new("1", (40, height), 0)
        ImageDraw.Draw(im).text((pad, 0), ch, font=font, fill=1)
        rows, width = [], 0
        for y in range(height):
            bits = 0
            for x in range(32):
                if im.getpixel((x + pad, y)):
                    bits |= 1 << (31 - x)
                    width = max(width, x + 1)
            rows.append(bits)
        advances.append(min(adv, 255))
        widths.append(width)
        bitmaps.append(rows)
    with open(out, "wb") as f:
        f.write(b"MFNT" + struct.pack("<HHHHI", height, ascent, 32, 256, 0))
        f.write(bytes(advances))
        f.write(bytes(widths))
        for rows in bitmaps:
            f.write(struct.pack("<%dI" % height, *rows))

def main():
    if len(sys.argv) == 5 and sys.argv[1] == "mfnt":
        gen_mfnt(sys.argv[2], int(sys.argv[3]), sys.argv[4])
        return
    font = load_font()
    lines = []
    lines.append("/* Generated by tools/genfont/genfont.py from 7x14.pcf.gz. Do not edit. */")
    lines.append("#include <drivers/font.h>")
    lines.append("")
    lines.append("const uint8_t font8x16[256][FONT_HEIGHT] = {")
    for code in range(256):
        glyph = render(font, code) if code >= 32 and code != 127 else [0] * CELL_H
        label = chr(code) if 32 <= code < 127 else ""
        comment = " /* %s */" % label.replace("*/", "* /") if label else ""
        lines.append("    [%d] = { %s },%s" % (code, ", ".join("0x%02x" % b for b in glyph), comment))
    lines.append("};")
    sys.stdout.write("\n".join(lines) + "\n")

if __name__ == "__main__":
    main()
