#pragma once
/* errno lives in the calling thread's control block (M35). */
int *__errno_location(void);
#define errno (*__errno_location())

#define EPERM        1
#define ENOENT       2
#define ESRCH        3
#define EINTR        4
#define EIO          5
#define ENXIO        6
#define E2BIG        7
#define ENOEXEC      8
#define EBADF        9
#define ECHILD      10
#define EAGAIN      11
#define ENOMEM      12
#define EACCES      13
#define EFAULT      14
#define EBUSY       16
#define EEXIST      17
#define EXDEV       18
#define ENODEV      19
#define ENOTDIR     20
#define EISDIR      21
#define EINVAL      22
#define ENFILE      23
#define EMFILE      24
#define ENOTTY      25
#define ETXTBSY     26
#define EFBIG       27
#define ENOSPC      28
#define ESPIPE      29
#define EDEADLK     35
#define EROFS       30
#define EMLINK      31
#define EPIPE       32
#define EDOM        33
#define ERANGE      34
#define ENAMETOOLONG 36
#define ENOSYS      38
#define ENOTEMPTY   39
#define ELOOP       40
#define EOVERFLOW   75
#define EBADMSG     74
#define EILSEQ      84
#define EMSGSIZE    90
#define EPROTONOSUPPORT 93
#define EOPNOTSUPP  95
#define ENOTSUP     EOPNOTSUPP       /* POSIX, with the same value as on Linux */
#define EAFNOSUPPORT 97
#define EADDRINUSE  98
#define ENOTSOCK    88
#define ECONNRESET  104
#define EISCONN     106
#define ENOTCONN    107
#define ETIMEDOUT   110
#define ECONNREFUSED 111
#define EWOULDBLOCK EAGAIN
/* N01: the remaining socket errors of a POSIX stack. */
#define EDESTADDRREQ 89
#define EPROTOTYPE   91
#define ENOPROTOOPT  92
#define ESOCKTNOSUPPORT 94
#define EADDRNOTAVAIL 99
#define ENETDOWN     100
#define ENETUNREACH  101
#define ENETRESET    102
#define ECONNABORTED 103
#define ENOBUFS      105
#define ESHUTDOWN    108
#define EHOSTDOWN    112
#define EHOSTUNREACH 113
#define EALREADY     114
#define EINPROGRESS  115
