# Utility test, run as: sh /etc/tests/utils.sh. Every failing check prints
# a line starting with FAIL.
printf 'banana\napple\ncherry\napple\n' > /u.txt
test "$(sort /u.txt | uniq | tr '\n' ' ')" = "apple banana cherry " || echo "FAIL sort-uniq"
test "$(sort -u /u.txt | wc -l | tr -d ' ')" = "3" || echo "FAIL sort-u"
test "$(sort -rn /dev/null | wc -l | tr -d ' ')" = "0" || echo "FAIL sort-empty"
test "$(grep -c apple /u.txt)" = "2" || echo "FAIL grep-c"
test "$(grep -n cherry /u.txt)" = "3:cherry" || echo "FAIL grep-n"
test "$(grep -vi APPLE /u.txt | tr '\n' ',')" = "banana,cherry," || echo "FAIL grep-vi"
test "$(tail -n 1 /u.txt)" = "apple" || echo "FAIL tail"
test "$(head -n 1 /u.txt | rev)" = "ananab" || echo "FAIL rev"
test "$(seq 3 | tr '\n' '+')" = "1+2+3+" || echo "FAIL seq"
test "$(seq 2 2 6 | nl | cut -f2 | tr '\n' ' ')" = "2 4 6 " || echo "FAIL nl-cut"
test "$(echo a:b:c | cut -d: -f2,3)" = "b:c" || echo "FAIL cut-fields"
test "$(echo abcdef | cut -c2-4)" = "bcd" || echo "FAIL cut-chars"
test "$(echo hello | tr a-z A-Z)" = "HELLO" || echo "FAIL tr"
test "$(echo aabbcc | tr -s abc)" = "abc" || echo "FAIL tr-s"
test "$(expr 2 + 3 '*' 4)" = "14" || echo "FAIL expr"
test "$(expr '(' 2 + 3 ')' '*' 4)" = "20" || echo "FAIL expr-paren"
test "$(expr 7 % 3)" = "1" || echo "FAIL expr-mod"
test "$(expr 3 '<' 5)" = "1" || echo "FAIL expr-cmp"
test "$(basename /bin/sh)" = "sh" || echo "FAIL basename"
test "$(basename /tmp/file.txt .txt)" = "file" || echo "FAIL basename-suffix"
test "$(dirname /bin/sh)" = "/bin" || echo "FAIL dirname"
test "$(dirname sh)" = "." || echo "FAIL dirname-dot"
test "$(echo copy | tee /u2.txt)" = "copy" || echo "FAIL tee"
test "$(cat /u2.txt)" = "copy" || echo "FAIL tee-file"
test "$(printf 'x\nx\ny\n' | uniq -c | tr -s ' ' | tr '\n' ';')" = " 2 x; 1 y;" || echo "FAIL uniq-c"
test "$(which sh)" = "/bin/sh" || echo "FAIL which"
test "$(env FOO=bar printenv FOO)" = "bar" || echo "FAIL env"
test "$(yes | head -n 2 | tr '\n' ' ')" = "y y " || echo "FAIL yes"
cmp /u.txt /u.txt > /dev/null || echo "FAIL cmp-same"
printf 'banana\napple\ncherry\n' > /u3.txt
cmp /u.txt /u3.txt > /dev/null && echo "FAIL cmp-differ"
test "$(diff /u.txt /u3.txt | tail -n 1)" = "< apple" || echo "FAIL diff"
test "$(life -q -g 4 -w 8 -h 8 | tail -n 1 | cut -d, -f1)" = "generation 4" || echo "FAIL life"
test "$(maze 3 2 7 | wc -l | tr -d ' ')" = "5" || echo "FAIL maze"
test "$(mandel 10 3 | wc -l | tr -d ' ')" = "3" || echo "FAIL mandel"
test "$(banner a | wc -l | tr -d ' ')" = "14" || echo "FAIL banner"
test "$(cowsay hi | head -n 2 | tail -n 1)" = "< hi >" || echo "FAIL cowsay"
test "$(fortune | wc -l | tr -d ' ')" != "0" || echo "FAIL fortune"
test "$(stat /u.txt | grep -c Size)" = "1" || echo "FAIL stat"
ln /u.txt /u4.txt
test "$(cat /u4.txt | wc -l | tr -d ' ')" = "4" || echo "FAIL ln"
test "$(du -s /u.txt | cut -f1)" = "1" || echo "FAIL du"
test "$(uptime | cut -d' ' -f1)" = "up" || echo "FAIL uptime"
test "$(free | grep -c Mem)" = "1" || echo "FAIL free"
test "$(uname)" = "minios" || echo "FAIL uname"
test "$(uname -m)" = "x86_64" || echo "FAIL uname-m"
test "$(uname -a | wc -w | tr -d ' ')" = "6" || echo "FAIL uname-a"
test -f /u.txt || echo "FAIL test-f"
test -d /bin || echo "FAIL test-d"
test 3 -lt 5 || echo "FAIL test-lt"
test ! -e /nonexistent || echo "FAIL test-not"
rm /u.txt /u2.txt /u3.txt /u4.txt
echo "utils: done"
