#pragma once
/* System call numbers, shared with libc. Arguments follow the SysV order:
 * rdi, rsi, rdx, r10, r8, r9. The number goes in rax, the result comes
 * back in rax as a negative errno on failure. */
#define SYS_write          1
#define SYS_exit           2
#define SYS_getpid         3
#define SYS_yield          4
#define SYS_fork           5
#define SYS_execve         6
#define SYS_wait4          7
#define SYS_kill           8
#define SYS_getppid        9
#define SYS_thread_create 10
#define SYS_thread_exit   11
#define SYS_thread_join   12
#define SYS_read          13
#define SYS_sbrk          14
#define SYS_chdir         15
#define SYS_getcwd        16
#define SYS_open          17
#define SYS_close         18
#define SYS_lseek         19
#define SYS_dup           20
#define SYS_dup2          21
#define SYS_stat          22
#define SYS_fstat         23
#define SYS_getdents      24
#define SYS_mkdir         25
#define SYS_unlink        26
#define SYS_rmdir         27
#define SYS_rename        28
#define SYS_pipe          29
#define SYS_link          30
#define SYS_mount         31
#define SYS_umount        32
#define SYS_sync          33
#define SYS_reboot        34
#define SYS_mmap          35
#define SYS_munmap        36
#define SYS_sigaction     37
#define SYS_sigprocmask   38
#define SYS_sigreturn     39
#define SYS_setpgid       40
#define SYS_getpgid       41
#define SYS_tcsetpgrp     42
#define SYS_tcgetpgrp     43
#define SYS_ioctl         44
#define SYS_sleep_ms      45
#define SYS_mq_open       46
#define SYS_mq_unlink     47
#define SYS_shm_open      48
#define SYS_shm_unlink    49
#define SYS_poll          50
#define SYS_uptime_ms     51
#define SYS_nproc         52
#define SYS_getcpu        53
#define SYS_uname         54
#define SYS_socket        55
#define SYS_socketpair    56
#define SYS_bind          57
#define SYS_listen        58
#define SYS_accept        59
#define SYS_connect       60
#define SYS_sendmsg       61
#define SYS_recvmsg       62
#define SYS_shutdown      63
#define SYS_memfd_create  64
#define SYS_ftruncate     65
#define SYS_eventfd       66
#define SYS_timerfd_create 67
#define SYS_timerfd_settime 68
#define SYS_timerfd_gettime 69
#define SYS_fcntl         70
#define SYS_pipe2         71
#define SYS_set_tls       72
#define SYS_futex         73
#define SYS_clock_gettime 74
#define SYS_clock_settime 75
#define SYS_gettid        76
#define SYS_MAX           77
