#!/bin/sh
# usage: version.sh <top> <out.c>
# Writes the kernel's identification source: the release from VERSION
# (semantic versioning, MAJOR.MINOR.PATCH), the build number from
# BUILDNUM (incremented here on every kernel link; the file is local to
# the working tree and not in git), the git commit and the date.
set -e
TOP="$1"
OUT="$2"
RELEASE="$(tr -d ' \n' < "$TOP/VERSION")"
N="$(cat "$TOP/BUILDNUM" 2>/dev/null || echo 0)"
N=$((N + 1))
echo "$N" > "$TOP/BUILDNUM"
COMMIT="$(git -C "$TOP" rev-parse --short HEAD 2>/dev/null || echo unknown)"
if [ "$COMMIT" != unknown ] && ! git -C "$TOP" diff-index --quiet HEAD -- 2>/dev/null; then
    COMMIT="$COMMIT-dirty"
fi
DATE="$(date -u +%Y-%m-%d)"
cat > "$OUT" <<END
/* Generated by tools/version.sh at every kernel link. */
#include <kernel.h>

const char kernel_release[] = "$RELEASE";
const char kernel_version[] = "#$N $COMMIT $DATE";
const unsigned kernel_build_number = $N;
END
